name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: yarn build

    - name: Start the server
      run: yarn start

    - name: analyze
      run: yarn lint

    - name: Run tests
      run: yarn tests

    - name: Format code
      run: yarn format:check

    - name: build docs
      run: mkdocs build
