name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm build

    - name: Start the server
      run: npm start

    - name: analyze
      run: npm lint

    - name: Run tests
      run: npm tests

    - name: Format code
      run: npm format:check

    - name: build docs
      run: mkdocs build
